[manifest]
version = "1.0.0"
dump_lua = true
priority = -10


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
    if AUT.info then
'''
position = "before"
payload = '''
    for k, v in pairs(SMODS.ObjectTypes) do
        if card.config.center.pools and card.config.center.pools[v.key] and v.pool_badge then
            if not badges[v.pool_badge] then
                badges[#badges+1] = v.pool_badge()
            end
        end
    end
'''
match_indent = true

