[manifest]
version = "1.0.0"
dump_lua = true
priority = -10


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
    if AUT.info then
'''
position = "before"
payload = '''
    for k, v in pairs(SMODS.ObjectTypes) do
        if card.config.center and card.config.center.pools and card.config.center.pools[v.key] and v.pool_badge then
            badges[#badges+1] = v.pool_badge()
        end
    end
    for k, v in pairs(SMODS.Attributes) do
        if card.config.center and card.config.center.attributes and card.config.center.attributes[k] and v.attribute_badge then
            badges[#badges+1] = v.attribute_badge()
        end
    end
'''
match_indent = true

